// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['tinyword.App'], ['goog.ds.DataManager', 'goog.ds.JsDataSource', 'goog.events.EventHandler'], {});
